sequenceDiagram
    actor Client
    participant PPR as 인기 상품 리스트 조회
    participant TSD as TopSaleData
    participant PTS as Product
    Client ->> PPR: 인기 상품 리스트 조회 요청
    PPR ->> TSD: 인기 상품 리스트 조회
    TSD ->> PTS: 상품 정보 조회
    PTS ->> TSD: 상품 정보 반환
    TSD ->> PPR: 인기 상품 정보 리스트 결과 반환
    PPR ->> Client: 인기 상품 정보 리스트 결과 반환